//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.AdminResources", typeof(AdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Model_IsActive {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Model_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Model_Level {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Model_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Model_Name {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Table_Column_Description {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Table_Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Table_Column_IsActive {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Table_Column_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Table_Column_Level {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Table_Column_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_Table_Column_Name {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_Table_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group.
        /// </summary>
        public static string Admin_AdminGroupUser_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_AdminGroupUser_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Description.
        /// </summary>
        public static string Admin_Config_Index_Model_Description {
            get {
                return ResourceManager.GetString("Admin_Config_Index_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Name.
        /// </summary>
        public static string Admin_Config_Index_Model_Name {
            get {
                return ResourceManager.GetString("Admin_Config_Index_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page English Name.
        /// </summary>
        public static string Admin_Config_Page_Model_EnglishName {
            get {
                return ResourceManager.GetString("Admin_Config_Page_Model_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is show in menu?.
        /// </summary>
        public static string Admin_Config_Page_Model_IsShowInMenu {
            get {
                return ResourceManager.GetString("Admin_Config_Page_Model_IsShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Module.
        /// </summary>
        public static string Admin_Config_Page_Model_ModuleSelect {
            get {
                return ResourceManager.GetString("Admin_Config_Page_Model_ModuleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string Admin_Config_Page_Model_Name {
            get {
                return ResourceManager.GetString("Admin_Config_Page_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string Admin_Config_Page_Model_OrderNo {
            get {
                return ResourceManager.GetString("Admin_Config_Page_Model_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Admin_Config_Page_Model_SeoLink {
            get {
                return ResourceManager.GetString("Admin_Config_Page_Model_SeoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter necessary name.
        /// </summary>
        public static string Admin_Necessary_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_Necessary_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary.
        /// </summary>
        public static string Admin_Necessary_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_Necessary_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created .
        /// </summary>
        public static string Admin_Necessary_Model_CreatedDate {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_Necessary_Model_Des {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name.
        /// </summary>
        public static string Admin_Necessary_Model_Name {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Admin_Necessary_Model_Number {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Admin_Necessary_Model_Price {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_Necessary_Model_SalonId {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_SalonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon name.
        /// </summary>
        public static string Admin_Necessary_Model_SalonName {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_SalonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose salon.
        /// </summary>
        public static string Admin_Necessary_Model_Select_Text {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop ID.
        /// </summary>
        public static string Admin_Necessary_Model_ShopId {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Admin_Necessary_Model_ShopName {
            get {
                return ResourceManager.GetString("Admin_Necessary_Model_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary Manager.
        /// </summary>
        public static string Admin_NecessaryManage_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created .
        /// </summary>
        public static string Admin_NecessaryManage_Model_DateCreated {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_NecessaryManage_Model_Des {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Admin_NecessaryManage_Model_EndDate {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grantor.
        /// </summary>
        public static string Admin_NecessaryManage_Model_GrantorName {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_GrantorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary ID.
        /// </summary>
        public static string Admin_NecessaryManage_Model_NecessaryId {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_NecessaryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary.
        /// </summary>
        public static string Admin_NecessaryManage_Model_NecessaryName {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_NecessaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Admin_NecessaryManage_Model_Number {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string Admin_NecessaryManage_Model_ReceiverName {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon ID.
        /// </summary>
        public static string Admin_NecessaryManage_Model_SalonId {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_SalonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string Admin_NecessaryManage_Model_SalonName {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_SalonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose salon.
        /// </summary>
        public static string Admin_NecessaryManage_Model_Select_Text {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop ID.
        /// </summary>
        public static string Admin_NecessaryManage_Model_ShopId {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Admin_NecessaryManage_Model_ShopName {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Admin_NecessaryManage_Model_StartDate {
            get {
                return ResourceManager.GetString("Admin_NecessaryManage_Model_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new role.
        /// </summary>
        public static string Admin_Role_Index_View_Add {
            get {
                return ResourceManager.GetString("Admin_Role_Index_View_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string Admin_Role_Index_View_Edit {
            get {
                return ResourceManager.GetString("Admin_Role_Index_View_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter role name.
        /// </summary>
        public static string Admin_Role_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_Role_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role dashboard.
        /// </summary>
        public static string Admin_Role_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_Role_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Admin_Salon_Index_Model_Address {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy name.
        /// </summary>
        public static string Admin_Salon_Index_Model_DeputyName {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_DeputyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_Salon_Index_Model_Des {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Admin_Salon_Index_Model_Email {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Admin_Salon_Index_Model_FacebookUrl {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Admin_Salon_Index_Model_Fax {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google plus.
        /// </summary>
        public static string Admin_Salon_Index_Model_GooglePlus {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_GooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List service.
        /// </summary>
        public static string Admin_Salon_Index_Model_ListServiceId {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_ListServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live chat.
        /// </summary>
        public static string Admin_Salon_Index_Model_LiveChat {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_LiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Admin_Salon_Index_Model_Location {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon name.
        /// </summary>
        public static string Admin_Salon_Index_Model_Name {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Admin_Salon_Index_Model_Phone {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinterest.
        /// </summary>
        public static string Admin_Salon_Index_Model_Pinterest {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Pinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Admin_Salon_Index_Model_ShopId {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string Admin_Salon_Index_Model_StateProvinceId {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_StateProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Admin_Salon_Index_Model_Twitter {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working date.
        /// </summary>
        public static string Admin_Salon_Index_Model_WorkingDate {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_Model_WorkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Admin_Salon_Index_View_Button_Services {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_Button_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Admin_Salon_Index_View_Button_Users {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_Button_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        public static string Admin_Salon_Index_View_GoogleMap {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        public static string Admin_Salon_Index_View_GoogleMap_SearchAddress {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_GoogleMap_SearchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter salon name.
        /// </summary>
        public static string Admin_Salon_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Admin_Salon_Index_View_Service_ServiceName {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_Service_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select service.
        /// </summary>
        public static string Admin_Salon_Index_View_Service_Title {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_Service_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string Admin_Salon_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_Salon_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_SalonRoom_Index_Model_Description {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_SalonRoom_Index_Model_Name {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Admin_SalonRoom_Index_Model_Priority {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_Model_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string Admin_SalonRoom_Index_Model_SalonId {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_Model_SalonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_SalonRoom_Index_SalonRoom_Table_Column_Description {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_SalonRoom_Table_Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_SalonRoom_Index_SalonRoom_Table_Column_Name {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_SalonRoom_Table_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Admin_SalonRoom_Index_SalonRoom_Table_Column_Priority {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_SalonRoom_Table_Column_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon name.
        /// </summary>
        public static string Admin_SalonRoom_Index_SalonRoom_Table_Column_SalonName {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_SalonRoom_Table_Column_SalonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter salon room name.
        /// </summary>
        public static string Admin_SalonRoom_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon room.
        /// </summary>
        public static string Admin_SalonRoom_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_SalonRoom_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Model_ChairName {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Model_ChairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Model_Des {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Model_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Model_Priority {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Model_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Model_RoomId {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Model_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Table_Column_ChairName {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Table_Column_ChairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Table_Column_Des {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Table_Column_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Table_Column_Priority {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Table_Column_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_Table_Column_RoomName {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_Table_Column_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter chair name.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon room chair.
        /// </summary>
        public static string Admin_SalonRoomChair_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChair_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chair name.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_ChairName {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_ChairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date checkout.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_Date {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End hour.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_EndHour {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End minute.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_EndMinute {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_EndMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_RoomName {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon name.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_SalonName {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_SalonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start hour.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_StartHour {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minute.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_StartMinute {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_StartMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_Table_Column_Status {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_Table_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon room chair manager.
        /// </summary>
        public static string Admin_SalonRoomChairManager_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_SalonRoomChairManager_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Admin_User_Index_Model_Address {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address full.
        /// </summary>
        public static string Admin_User_Index_Model_AddressFull {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_AddressFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Admin_User_Index_Model_Birthday {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Admin_User_Index_Model_City {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Admin_User_Index_Model_District {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Admin_User_Index_Model_Email {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Purse number.
        /// </summary>
        public static string Admin_User_Index_Model_EpurseNumber {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_EpurseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Admin_User_Index_Model_FullName {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Admin_User_Index_Model_Gender {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group.
        /// </summary>
        public static string Admin_User_Index_Model_Group {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card.
        /// </summary>
        public static string Admin_User_Index_Model_IdentityCard {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_IdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin_User_Index_Model_IsAdmin {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Admin_User_Index_Model_Location {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage.
        /// </summary>
        public static string Admin_User_Index_Model_Marriage {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Admin_User_Index_Model_Mobile {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_User_Index_Model_Name {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Admin_User_Index_Model_Password {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Admin_User_Index_Model_Status {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Admin_User_Index_Model_UserName {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        public static string Admin_User_Index_Model_Ward {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string Admin_User_Index_Model_ZipCode {
            get {
                return ResourceManager.GetString("Admin_User_Index_Model_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Admin_User_Index_User_Table_Column_Email {
            get {
                return ResourceManager.GetString("Admin_User_Index_User_Table_Column_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Admin_User_Index_User_Table_Column_FullName {
            get {
                return ResourceManager.GetString("Admin_User_Index_User_Table_Column_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Admin_User_Index_User_Table_Column_Mobile {
            get {
                return ResourceManager.GetString("Admin_User_Index_User_Table_Column_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Admin_User_Index_User_Table_Column_Name {
            get {
                return ResourceManager.GetString("Admin_User_Index_User_Table_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Admin_User_Index_User_Table_Column_UserName {
            get {
                return ResourceManager.GetString("Admin_User_Index_User_Table_Column_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name.
        /// </summary>
        public static string Admin_User_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_User_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Admin_User_Index_View_Title {
            get {
                return ResourceManager.GetString("Admin_User_Index_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user group name.
        /// </summary>
        public static string Admin_UserGroup_Index_View_Input_Keyword_Placeholder {
            get {
                return ResourceManager.GetString("Admin_UserGroup_Index_View_Input_Keyword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Shop_Index_Create_Model_Address {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressFull.
        /// </summary>
        public static string Shop_Index_Create_Model_Addressfull {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Addressfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Shop_Index_Create_Model_CityId {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeputyName.
        /// </summary>
        public static string Shop_Index_Create_Model_DeputyName {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_DeputyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Shop_Index_Create_Model_Des {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Shop_Index_Create_Model_DistrictId {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_DistrictId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Shop_Index_Create_Model_Email {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Shop_Index_Create_Model_Fax {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Shop_Index_Create_Model_Mobile {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Shop_Index_Create_Model_Name {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Management.
        /// </summary>
        public static string Shop_Index_Create_Model_UserId {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        public static string Shop_Index_Create_Model_WardId {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Model_WardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shop.
        /// </summary>
        public static string Shop_Index_Create_Title {
            get {
                return ResourceManager.GetString("Shop_Index_Create_Title", resourceCulture);
            }
        }
    }
}
