//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Login_Model_Password {
            get {
                return ResourceManager.GetString("Account_Login_Model_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Account_Login_Model_RememberMe {
            get {
                return ResourceManager.GetString("Account_Login_Model_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Account_Login_Model_UserName {
            get {
                return ResourceManager.GetString("Account_Login_Model_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string List_Payroll_Formula_Employe_Formula {
            get {
                return ResourceManager.GetString("List_Payroll_Formula_Employe_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string List_Payroll_Formula_Employe_Salary {
            get {
                return ResourceManager.GetString("List_Payroll_Formula_Employe_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string List_Payroll_Formula_Employe_Salon {
            get {
                return ResourceManager.GetString("List_Payroll_Formula_Employe_Salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string List_Payroll_Formula_Employe_User {
            get {
                return ResourceManager.GetString("List_Payroll_Formula_Employe_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Payroll Formula of Employee.
        /// </summary>
        public static string List_Payroll_Formula_Employee {
            get {
                return ResourceManager.GetString("List_Payroll_Formula_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage payroll formula of employee.
        /// </summary>
        public static string List_Payroll_Formula_Employee_Manage {
            get {
                return ResourceManager.GetString("List_Payroll_Formula_Employee_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Service.
        /// </summary>
        public static string List_Service {
            get {
                return ResourceManager.GetString("List_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Service.
        /// </summary>
        public static string List_Service_id {
            get {
                return ResourceManager.GetString("List_Service_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string List_Service_Key {
            get {
                return ResourceManager.GetString("List_Service_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketPrice.
        /// </summary>
        public static string List_Service_MarketPrice {
            get {
                return ResourceManager.GetString("List_Service_MarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string List_Service_Name {
            get {
                return ResourceManager.GetString("List_Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string List_Service_Price {
            get {
                return ResourceManager.GetString("List_Service_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string List_Service_Salon {
            get {
                return ResourceManager.GetString("List_Service_Salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string List_Service_Status {
            get {
                return ResourceManager.GetString("List_Service_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string List_Service_Status_No {
            get {
                return ResourceManager.GetString("List_Service_Status_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string List_Service_Status_Yes {
            get {
                return ResourceManager.GetString("List_Service_Status_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Formula Of User.
        /// </summary>
        public static string Payroll_Formula_Employee {
            get {
                return ResourceManager.GetString("Payroll_Formula_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Formula.
        /// </summary>
        public static string Payroll_Formula_FormulaId {
            get {
                return ResourceManager.GetString("Payroll_Formula_FormulaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min From.
        /// </summary>
        public static string Payroll_Formula_From {
            get {
                return ResourceManager.GetString("Payroll_Formula_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Payroll_Formula_Price {
            get {
                return ResourceManager.GetString("Payroll_Formula_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Payroll_Formula_Salary {
            get {
                return ResourceManager.GetString("Payroll_Formula_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string Payroll_Formula_SalonId {
            get {
                return ResourceManager.GetString("Payroll_Formula_SalonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Payroll_Formula_ShopId {
            get {
                return ResourceManager.GetString("Payroll_Formula_ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Payroll_Formula_Type {
            get {
                return ResourceManager.GetString("Payroll_Formula_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Payroll_Formula_UserId {
            get {
                return ResourceManager.GetString("Payroll_Formula_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketPrice.
        /// </summary>
        public static string Service_Create_MarketPrice {
            get {
                return ResourceManager.GetString("Service_Create_MarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        public static string Service_Create_MetaKeywords {
            get {
                return ResourceManager.GetString("Service_Create_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Title.
        /// </summary>
        public static string Service_Create_MetaTitle {
            get {
                return ResourceManager.GetString("Service_Create_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Service_Create_Name {
            get {
                return ResourceManager.GetString("Service_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Service_Create_Price {
            get {
                return ResourceManager.GetString("Service_Create_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeoLink.
        /// </summary>
        public static string Service_Create_SeoLink {
            get {
                return ResourceManager.GetString("Service_Create_SeoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Service_Create_Summary {
            get {
                return ResourceManager.GetString("Service_Create_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsign Name.
        /// </summary>
        public static string Service_Create_UnsignName {
            get {
                return ResourceManager.GetString("Service_Create_UnsignName", resourceCulture);
            }
        }
    }
}
